server:
  port: 0
spring:
  application:
    name: ms-2-ws
  boot:
    admin:
      client:
        url:
        - http://admin:admin@localhost:8761/admin
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:mysql://localhost:3306/cs_db
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'